apiVersion: v1
kind: Service
metadata:
  name: lab4-web-service
spec:
  type: NodePort
  selector:
    app:  lab4-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008
