apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-web-deployment
  labels:
    app: lab4-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4-web
  template:
    metadata:
      labels:
        app: lab4-web
    spec:
      containers:
      - name: webserver-container
        image: localhost:32000/webserver:registry
        ports:
        - containerPort: 8000
