kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  labels:
    app: mongodb
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: .5Gi
  accessModes:
      - ReadWriteOnce
  hostPath:
    path: /var/snap/microk8s/common/default-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongodb
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: .5Gi