apiVersion: v1
kind: Service
metadata:
  name: lab8-web-service
spec:
  type: NodePort
  selector:
    app:  lab8-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
