apiVersion: v1
kind: Service
metadata:
  name: lab12-web-service
spec:
  type: NodePort
  selector:
    app:  lab12-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30010
